# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0b510a493fc4f363856d8be56da264df"
name = "Calculator V2.1"
handle = "calculator-v2-1"
application_url = "https://winner-juan-surprise-happiness.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_metaobjects,write_metaobject_definitions"

[auth]
redirect_urls = ["https://winner-juan-surprise-happiness.trycloudflare.com/auth/callback", "https://winner-juan-surprise-happiness.trycloudflare.com/auth/shopify/callback", "https://winner-juan-surprise-happiness.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
